// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwdMlgt955IHN2uXugjMuOmepoxtxE-GE',
    appId: '1:179711535828:web:96a0a6fefeb73caf5ae941',
    messagingSenderId: '179711535828',
    projectId: 'dstek-test',
    authDomain: 'dstek-test.firebaseapp.com',
    storageBucket: 'dstek-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvjadD0YW17Q3nfRwzSoQtBxLzBzgpbAw',
    appId: '1:179711535828:android:6139438c264d96d85ae941',
    messagingSenderId: '179711535828',
    projectId: 'dstek-test',
    storageBucket: 'dstek-test.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1jBhb4x1_pXOS5wpJfiuIoeYHZ23n9dc',
    appId: '1:179711535828:ios:02b92cd76b4560d85ae941',
    messagingSenderId: '179711535828',
    projectId: 'dstek-test',
    storageBucket: 'dstek-test.firebasestorage.app',
    iosBundleId: 'com.example.dstek',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1jBhb4x1_pXOS5wpJfiuIoeYHZ23n9dc',
    appId: '1:179711535828:ios:02b92cd76b4560d85ae941',
    messagingSenderId: '179711535828',
    projectId: 'dstek-test',
    storageBucket: 'dstek-test.firebasestorage.app',
    iosBundleId: 'com.example.dstek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwdMlgt955IHN2uXugjMuOmepoxtxE-GE',
    appId: '1:179711535828:web:d0c3689c6edfe5925ae941',
    messagingSenderId: '179711535828',
    projectId: 'dstek-test',
    authDomain: 'dstek-test.firebaseapp.com',
    storageBucket: 'dstek-test.firebasestorage.app',
  );
}
