// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXthvUyjz4eJT8vGu_GktH-TwgfZLGK0I',
    appId: '1:745081783885:web:63d343fc29650106b77e04',
    messagingSenderId: '745081783885',
    projectId: 'dstek-f4235',
    authDomain: 'dstek-f4235.firebaseapp.com',
    storageBucket: 'dstek-f4235.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBltZcS86YvQx-7TE3g589GwuaENLkSLc',
    appId: '1:745081783885:android:3822184168a44317b77e04',
    messagingSenderId: '745081783885',
    projectId: 'dstek-f4235',
    storageBucket: 'dstek-f4235.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7aj_hCdtzGl-Vjf4GWm5gEtF8nTvTn3U',
    appId: '1:745081783885:ios:0feb326e9e35bce9b77e04',
    messagingSenderId: '745081783885',
    projectId: 'dstek-f4235',
    storageBucket: 'dstek-f4235.firebasestorage.app',
    iosBundleId: 'com.example.dstek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7aj_hCdtzGl-Vjf4GWm5gEtF8nTvTn3U',
    appId: '1:745081783885:ios:0feb326e9e35bce9b77e04',
    messagingSenderId: '745081783885',
    projectId: 'dstek-f4235',
    storageBucket: 'dstek-f4235.firebasestorage.app',
    iosBundleId: 'com.example.dstek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXthvUyjz4eJT8vGu_GktH-TwgfZLGK0I',
    appId: '1:745081783885:web:aa0735f513232052b77e04',
    messagingSenderId: '745081783885',
    projectId: 'dstek-f4235',
    authDomain: 'dstek-f4235.firebaseapp.com',
    storageBucket: 'dstek-f4235.firebasestorage.app',
  );
}
